/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    ProtocolInput: typeof import('./src/components/ProtocolInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionInfo: typeof import('./src/components/TransactionInfo.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
    WitnessInfo: typeof import('./src/components/WitnessInfo.vue')['default']
  }
}
